Excluding protobuf-javalite from the classpath.
bitcoinj-core 0.16 adds protobuf-javalite from the classpath
by default. Subzero uses protobuf-java as a dependency already.

Updating bitcoinj-core causes runtime failures as listed below:
java.lang.NoSuchMethodError: 'com.google.protobuf.Descriptors$Descriptor com.google.protobuf.Any.getDescriptor()'

This is because protobuf-javalite and protobuf-java are not ABI
compatible by definition.
The lite version seems to be used for android builds to reduce the
artefact size. For subzero we don't need that.