Nmahendru/bitcoinj 0 16 update tweek (#441)
* Bump bitcoinj-core from 0.15.10 to 0.16 in /java

Bumps [bitcoinj-core](https://github.com/bitcoinj/bitcoinj) from 0.15.10 to 0.16.
- [Release notes](https://github.com/bitcoinj/bitcoinj/releases)
- [Commits](https://github.com/bitcoinj/bitcoinj/compare/v0.15.10...v0.16)

---
updated-dependencies:
- dependency-name: org.bitcoinj:bitcoinj-core
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Excluding protobuf-javalite from the classpath.

bitcoinj-core 0.16 adds protobuf-javalite from the classpath
by default. Subzero uses protobuf-java as a dependency already.

Updating bitcoinj-core causes runtime failures as listed below:
java.lang.NoSuchMethodError: 'com.google.protobuf.Descriptors$Descriptor com.google.protobuf.Any.getDescriptor()'

This is because protobuf-javalite and protobuf-java are not ABI
compatible by definition.
The lite version seems to be used for android builds to reduce the
artefact size. For subzero we don't need that.

To get dependency list use:
```bash
mvn compile dependency:tree
```

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>